/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2013-04-30 00:12:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.text.SimpleDateFormat;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Hot meals steward</title>\r\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<style media=\"all\" type=\"text/css\">@import \"css/all.css\";</style>\r\n");
      out.write("\t<!--[if lt IE 7]><style media=\"screen\" type=\"text/css\">@import \"css/ie6.css\";</style><![endif]-->\r\n");
      out.write("\t <script defer type=\"text/javascript\" src=\"pngfix.js\"></script>\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<div class=\"background\">\r\n");
      out.write("\t\t\t\t<h1><a href=\"index.html\">Hot Meals Steward</a></h1>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<div id=\"leftcol\">\r\n");
      out.write("\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block-top\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block-content\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Featured restaurant of this week<span> SilverSpoons </span></h2>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"border-left-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"border-right-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"border-left-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"border-right-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"img/img-interier.jpg\" alt=\"Interier\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h2><a href=\"user.jsp\" style=\"color: #C0D765\" >Find out what your friends think</a></h2>\r\n");
      out.write("\t\t\t\t\t\t<h2><a href=\"graph.html\" style=\"color: #C0D765\" >The Story so far..</a></h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block-bottom\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"rightcol\">\r\n");
      out.write("\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block-top\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block-content\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Top<span>Rated</span></h3>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Indian.jsp\">Indian</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Korean.jsp\">Korean</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"greek.jsp\">Greek</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"med.jsp\">Mediterranean</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"chinese.jsp\">Chinese</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"french.jsp\">French</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Thai.jsp\">Thai</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jap.jsp\">Japanese</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mexican.jsp\">Mexican</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Italian.jsp\">Italian</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block-bottom\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<p>©2013 FoodSpotting.Design by Team HeadStart</a> </a></p>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"services.html\">Services </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"contact.html\">Contact us</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
